name: Build

on:
  workflow_dispatch:

jobs:
  linux-build:
    name: 'Linux'
    runs-on: 'ubuntu-latest'
    container: 'ubuntu:16.04'
    steps:
      - uses: actions/checkout@v3
      
      - run: apt update && apt upgrade -y && apt clean
        
      - run: apt update
      
      - run: apt-get install -y wget build-essential checkinstall  libreadline-gplv2-dev  libncursesw5-dev  libssl-dev  libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
      
      - run: cd /usr/src
      
      - run: sudo wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tgz
      
      - run: sudo tar xzf Python-3.8.10.tgz
        
      - run: cd Python-3.8.10
      
      - run: sudo ./configure --enable-optimizations
      
      - run: sudo make altinstall
      
      - name: check python version
        run: |
          python3.8 --version
          python3 --version

#       # from rashidnhm’s snippet @ https://github.com/actions/setup-python/issues/330
#       - id: setup_python
#         uses: actions/setup-python@v3
#         with:
#           python-version: 3.7

#       - id: python_cache
#         uses: actions/cache@v3
#         with:
#           path: venv
#           key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

#       - name: Install dependencies unless cached
#         if: steps.python_cache.outputs.cache-hit != 'true'
#         run: |
#           # Check if venv exists (restored from secondary keys if any, and delete)
#           if [ -d "venv" ]; then rm -rf venv; fi
#           # Re-create the venv
#           python3 -m venv venv
#           # Install dependencies
#           venv/bin/python3 -m pip install pyinstaller setuptools
#           venv/bin/python3 -m pip install -r requirements.txt

#       - name: Run setup script
#         run: venv/bin/python3 setup.py b -k onedir

#       - run: ls

#       - name: Upload the build artifacts
#         uses: actions/upload-artifact@v3.0.0
#         with:
#           name: retype-1.0.0-linux
#           path: ./dist/retype
#           if-no-files-found: error
#           retention-days: 1
