name: Build

on:
  workflow_dispatch:

jobs:
  linux-build:
    name: 'Linux'
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: ['ubuntu-20.04', 'ubuntu-18.04']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install pyinstaller setuptools
          pip3 install -r requirements.txt

      - name: Run setup script
        run: python3 setup.py b -k onedir

      - name: ls
        run: ls
